// <auto-generated />
namespace PotatoPortail.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_element_connaissance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_element_connaissance));
        
        string IMigrationMetadata.Id
        {
            get { return "201812120252339_update_element_connaissance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
