// <auto-generated />
namespace PotatoPortail.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modifs_models_eSports : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifs_models_eSports));
        
        string IMigrationMetadata.Id
        {
            get { return "201812092028597_modifs_models_eSports"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
